# apiVersion: v1
# kind: Service
# metadata:
#   name: load-balancer
#   labels:
#     app: react-docker
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
#       nodePort: 31000
#   selector:
#     app: react-docker

apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: react-docker
spec:
  selector:
    # app.kubernetes.io/name: MyApp
    app: react-docker
  ports:
    - protocol: TCP
      port: 80
      # targetPort: 9376
      targetPort: 80
      nodePort: 30001
  # clusterIP: 10.0.171.239
  type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#       - ip: 192.0.2.127
