import { env } from "../constants";

export const APP_VERSION = env?.VITE_APP_VERSION

export const TITLE = env?.VITE_APP_TITLE

export const TURN_URLS = env?.VITE_APP_TURN_URLS
export const TURN_USERNAME = env?.VITE_APP_TURN_USERNAME
export const TURN_CREDENTIALS = env?.VITE_APP_TURN_CREDENTIALS

export const SPOTIFY_CLIENT_ID = env?.VITE_APP_SPOTIFY_CLIENT_ID
export const SPOTIFY_REDIRECT_URI = env?.VITE_APP_SPOTIFY_REDIRECT_URI
export const SPOTIFY_AUTH_ENDPOINT = env?.VITE_APP_SPOTIFY_AUTH_ENDPOINT
export const SPOTIFY_RESPONSE_TYPE = env?.VITE_APP_SPOTIFY_RESPONSE_TYPE
